sudo: false

notifications:
  email:
    on_success: never
    on_failure: change

language: node_js
node_js:
  - stable
cache:
  yarn: true
  directories:
    - ~/.npm
    - .jest
script:
  - yarn run test
